config/routes.rb
Rails.application.routes.draw do
  constraints Clearance::Constraints::SignedIn.new do
    root to: 'entries#index', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'clearance/sessions#new'
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create, :show, :edit, :update] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get "/entries" => "entries#index", as: "entries"
  post "/entries" => "entries#create"
  get "/cities/:id/entries/new" => "entries#new", as: "new_entry"
  get "/entries/:id/edit" => "entries#edit", as: "edit_entry"
  get "/entries/:id" => "entries#show", as: "entry"
  put "/entries/:id" => "entries#update", as: "update_entry"
  delete "/entries/:id" => "entries#destroy"

  get '/cities/:id' => 'cities#show', as: 'city'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :users, through: :entries

  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]
  def should_generate_new_friendly_id?
    name_changed? || super
  end
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :city

  validates :title, presence: true, length: { maximum: 200, allow_nil: false, message: "Can't be nil" }
  validates :description, presence: true

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]
  def should_generate_new_friendly_id?
    title_changed? || super
  end

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  include Clearance::User
  has_many :entries, dependent: :destroy
  has_many :cities, through: :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.friendly.find(params[:id])
    @entries = Entry.where('city_id = ?', @city.id)
    @records = @entries.joins("INNER JOIN users ON entries.user_id = users.id").select("entries.id, entries.title, entries.description,entries.city_id,entries.user_id,entries.created_at, users.image,users.name")
    @records = @records.order(created_at: :desc)
  end
end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new, :edit, :update], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def show
    @user = user_from_params
    render template: "users/show"
  end

  def edit
    @user = current_user
    render template: "users/edit"
  end

  def update
    @user = current_user
    h = permit_params.to_h
    h.delete("password")
      if @user.update(h)
        redirect_to entries_path
      end
  end

  def create
    @user = user_from_params
    @user.image = "default-user-image.png" if @user.image.empty?

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    name = user_params.delete(:name)
    location = user_params.delete(:location)
    image = user_params.delete(:image)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.name = name
      user.location = location
      user.image = image
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end

  def permit_params
    params.require(:user).permit(:name, :email, :password, :location, :image)
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :require_login

  def index
    user_Id = current_user.id
    @entries = current_user.entries

    @records = @entries.joins("INNER JOIN cities ON entries.city_id = cities.id").select("entries.id, entries.title, entries.description,entries.city_id,entries.user_id,entries.created_at, cities.image")
    @records = @records.where(:user_id => current_user.id)
    @records = @records.order(created_at: :desc)
  end

  def new
    @entry = Entry.new
    @city = City.find(params[:id])
  end

  def edit
    @entry = Entry.find(params[:id])
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def update
    @entry = Entry.find(params[:id])
        if @entry.update entry_params
          redirect_to @entry
        end
  end

  def create
    @entry = current_user.entries.build(entry_params)

    if @entry.valid?
        @entry.save
        redirect_to @entry
      else
        @entry = Entry.create
        flash[:error] = "Oops! Title and description " + @entry.errors.messages[:title][0] + "."
        redirect_to new_entry_path(params[:entry][:city_id])
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to entries_path
  end

  private

     def entry_params
       params.require(:entry).permit(:title, :description, :city_id)
     end

     def city_params
       params.require(:city).permit(:id)
     end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/cities/show.html.erb
<section class="top-page">
<div class="bg">
  <%= image_tag "#{@city.image}", class: 'city-bg-img' %>
</div>

<div class="row city-name">
  <div class="col-sm-12">
    <h3 class="city-text"><%= @city.name %></h3>
    <p class="city-text"> <%= @city.country %></p>
  </div>
</div>
</section>


<div class="entries-container">
  <div class="col-sm-offset-1 col-sm-10 entries">
    <h1 class="headline"> Latest Posts
    <%= link_to 'New Post', new_entry_path, class: 'btn btn-default new-post' %>
    </h1>
    <% @records.each do |record| %>
    <div class="container-fluid entry">
      <div class="row ">
        <div class="city-img col-sm-2">
          <%= image_tag "#{record.image}", class: 'prof-icon' %>
        </div>

        <div class="entry-text col-sm-8">
          <h3 class="entry-title"><%= link_to record.title,  entry_path(record.id), class: 'entry-title-link' %></h3>
          <p class="entry-body"><%= record.description %></p>
        </div>
      </div>
      <div class="row btn-bar">


      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/entries/_form.html.erb
<div class="text-field form-group">
  <%= form.label :title %>
  <%= form.text_field :title, type: 'title', class: 'form-control', :required => true, placeholder: 'Title' %>
</div>

<div class="text-area form-group">
  <%= form.label :description %>
  <%= form.text_area :description, :rows => 10, style: 'width:100%', type: 'location', class: 'form-control', :required => true, placeholder: 'Description' %>
</div>

app/views/entries/edit.html.erb
<%= image_tag "#{@entry.city.image}", class: 'city-bg-img' %>

<div id='new_entry' class='new-entry-container'>
  <%= form_for(@entry, html: {method: 'put', class: 'form-horizontal col-sm-offset-2 col-sm-8 new-form'}  ) do |form| %>
    <div class='new-entry-form col-sm-offset-2 col-sm-8'>

      <%= render partial: '/entries/form', object: form %>

      <div class="submit-field">
        <%= form.submit 'Edit Entry', class: 'btn btn-default'%>
        <%= link_to 'Back', city_path(@entry.city_id), class: 'btn btn-default pull-right' %>
      </div>

    </div>
  <% end %>
</div>

app/views/entries/index.html.erb
      <div class="row profile">
        <div class="user-info col-sm-offset-2 col-sm-8">
          <%= image_tag(current_user.image, class: 'user-img') %>
          <h1 class="user-name"><%= current_user.name %> </h1>
          <p class="location">
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
            <%= current_user.location %>
          <p class="user-since">
            <span class="glyphicon glyphicon-star"></span>
            MC Elite since: <%= current_user.created_at.strftime("%m/%d/%Y") %>
          </p>
          <br>
          <ul class='city-nav'>
            <li class="city-list"><%= link_to 'San Francisco', '/cities/san-francisco', class: 'city-link' %></li>
            <li class="city-list"><%= link_to 'London', '/cities/london', class: 'city-link' %></li>
            <li class="city-list"><%= link_to 'Gibraltar', '/cities/gibraltar', class: 'city-link' %></li>
          </ul>
        </div>


      </div>

    <div class="entries-container container">
      <h1 class="headline"> Latest Posts </h1>
      <div class="col-sm-offset-2 col-sm-7 entries">
        <% @records.each do |record| %>
        <div class="container-fluid entry">
          <div class="row ">
            <div class="city-img col-sm-3">
              <%= image_tag(record.image, class: 'city-icon') %>
            </div>
            <div class="entry-text col-sm-8">
              <h3 class="entry-title"><%= link_to record.title,  entry_path(record.id), class: 'entry-title-link' %></h3>
              <p class="entry-body"><%= record.description %></p>
            </div>
          </div>
          <div class="row btn-bar">
            <div class="col-sm-offset-3 col-sm-8">

              <%= link_to edit_entry_path(record.id), class: 'btn btn-default edit-entry' do %>
                <i class='glyphicon glyphicon-pencil'></i>
              <% end %>
              <%= link_to entry_path(record.id), method: :delete, class: 'btn btn-default delete-entry', data: { confirm:'Are you sure you want to delete?' } do %>
                <i class='glyphicon glyphicon-trash'></i>
              <% end %>
              <%= link_to 'Read More',  entry_path(record.id), class: 'btn btn-default read-more' %>

            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>

app/views/entries/new.html.erb
  <%= image_tag "#{@city.image}", class: 'city-bg-img' %>


<div id='new_entry' class='new-entry-container'>
  <%= form_for(@entry, html: {class: 'form-horizontal col-sm-offset-2 col-sm-8 new-form-city'}  ) do |form| %>
    <div class='new-entry-form col-sm-offset-2 col-sm-8'>
      <div id="flash-entry">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>

      <%= render partial: '/entries/form', object: form %>
      <%= form.hidden_field :city_id, :value => @city.id %>

      <div class="submit-field">
        <%= form.submit 'New Entry', class: 'btn btn-default'%>
        <%= link_to 'Return to City', city_path, class: 'btn btn-default pull-right' %>
      </div>

    </div>
  <% end %>
</div>

app/views/entries/show.html.erb
<section class="city-show-grad">
  <%= image_tag "#{@entry.city.image}", class: 'city-bg-img' %>
  </section>

<div class="entries-container">
  <div class="col-sm-offset-1 col-sm-10 entries">

    <div class="container-fluid entry">
      <div class="row ">
        <div class="city-img col-sm-2">
          <%= image_tag(@entry.user.image, class: 'city-icon') %>
          <p class="author"> <%= @entry.user.name %> </p>
        </div>
        <div class="entry-text col-sm-8">
          <h3 class="entry-title"><%= link_to @entry.title,  entry_path(@entry.id), class: 'entry-title-link' %></h3>
          <p class="entry-body"><%= @entry.description %></p>
        </div>
      </div>
      <div class="row btn-bar">
        <div class="col-sm-offset-2 col-sm-8">
          <% if signed_in? && current_user.id == @entry.user.id %>
            <%= link_to edit_entry_path(@entry.id), class: 'btn btn-default edit-entry' do %>
              <i class='glyphicon glyphicon-pencil'></i>
            <% end %>
            <%= link_to entry_path(@entry.id), method: :delete, class: 'btn btn-default delete-entry', data: { confirm:'Are you sure you want to delete?' } do %>
              <i class='glyphicon glyphicon-trash'></i>
            <% end %>
          <% end %>
          <%= link_to 'Back',  entries_path, class: 'btn btn-default read-more' %>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VagabondApp</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,900" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="nav-bar navbar-fixed-top" id="startchange">
    <div class="container-fluid">
      <div class="navbar-header col-xs-12">
        <%= link_to 'Vagabond', entries_path, class: 'navbar-text navbar-left title' %>
        <% if signed_in? %>
          <%= button_to 'Sign out', sign_out_path, method: :delete, class: 'btn btn-default navbar-btn sign-out pull-right' %>
          <%= link_to edit_user_path(current_user), class: 'btn btn-default edit-profile pull-right' do %>
            <i class="glyphicon glyphicon-cog"></i>
          <% end %>
          <p class="user-nav"> <%= current_user.name %> </p>
        <% else %>
          <%= link_to 'Sign up', sign_up_path, class: 'btn btn-default sign-up navbar-btn pull-right' %>
        <% end %>
      </div>
    </div>
  </nav>


    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>


    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="text-field form-group">
  <%= form.label :name %>
  <%= form.text_field :name, type: 'name', class: 'form-control', :required => true, placeholder: 'Full Name' %>
</div>

<div class="text-field form-group">
  <%= form.label :location %>
  <%= form.text_field :location, type: 'location', class: 'form-control', :required => true, placeholder: 'Which city do you live in?' %>
</div>

<div class="text-field form-group">
  <%= form.label :image %>
  <%= form.text_field :image, class: 'form-control', placeholder: 'Please provide a link to url image.' %>
</div>

<div class="text-field form-group">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email', class: 'form-control', :required => true, placeholder: 'example@example.com' %>
</div>

app/views/users/edit.html.erb
<div id='new_user' class= 'edit-user-container'>

  <%= form_for(@user, html: { class: 'form-horizontal col-sm-offset-2 col-sm-8 new-form-user' }) do |form| %>
    <div class='sign-up-form col-sm-offset-2 col-sm-8'>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field">
        <%= form.submit 'Update User', class: 'btn btn-default'%>
        <%= link_to 'Back',  entries_path, class: 'btn btn-default pull-right' %>
      </div>



    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div id='new_user' class='sign-up-container'>


  <%= form_for(@user, html: { class: 'form-horizontal col-sm-offset-2 col-sm-8 new-form' }) do |form| %>
    <div class='sign-up-form col-sm-offset-2 col-sm-8'>

      <%= render partial: '/users/form', object: form %>

      <div class="password-field form-group">
        <%= form.label :password %>
        <%= form.password_field :password, class: 'form-control', :required => true, placeholder: 'Must be at least 4 characters.' %>
      </div>

      <div class="submit-field">
        <%= form.submit 'Sign Up', class: 'btn btn-default' %>
        <%= link_to 'Back', sign_in_path, class: 'btn btn-default' %>
      </div>

    </div>
  <% end %>

</div>

app/views/users/show.html.erb
<h1> <%= current_user.name %> </h1>